PLATFORM=linux
PROJECT=$(shell pwd)
NO-OS ?= $(realpath $(PROJECT)/../../../)

SRCS += $(PROJECT)/main.c

include $(NO-OS)/tools/scripts/generic_variables.mk
include ./src.mk
include $(NO-OS)/tools/scripts/generic.mk



